##==============================================================================
## Creates an ASS file from an Audacity's labels track
## Author: Laurens Rodriguez.
##------------------------------------------------------------------------------
use strict;
use warnings;

my $namefile = gets( "Labels track file" );

my $start = 0;
my $end = 0;

open( my $file, "<", $namefile ) or die( "Can't open [$namefile]: $!" );
open( my $ass, ">", $namefile . '.ass' ) or die( "Can't create ASS file: $!" );
print( $ass getHeader() );
while ( my $line = <$file> )
{
    $line = trim( $line );
    if ( $line =~ /([0-9\.]+)\t([0-9\.]+)\t(.+)/ )
    {
        $start = formatTime( $1 );
        $end = formatTime( $2 );
        print( $ass "Dialogue: 0,$start,$end,IScreenText,,0,0,0,,$3\n" );
    }
}
close( $file );
close( $ass );


##------------------------------------------------------------------------------
sub formatTime
{
    my $seconds = $_[0];
    my $time = '';
    my $hours = int( $seconds / 3600 );
    $seconds -= $hours * 3600;
    my $minutes = int( $seconds / 60 );
    $minutes = '0' . $minutes if ( $minutes < 10 );
    $seconds -= $minutes * 60;
    my $cents = $seconds;
    $seconds = int( $seconds );
    $seconds = '0' . $seconds if ( $seconds < 10 );
    $cents = int( 100 * ( $cents - $seconds ) );
    $cents = '0' . $cents if ( $cents < 10 );
    return "$hours:$minutes:$seconds.$cents";
}

##------------------------------------------------------------------------------
sub getHeader
{
    my $header = "";
    my $DATA_POS = tell( DATA );
    seek( DATA, $DATA_POS, 0 );
    while ( <DATA> )
    {
        $header .= $_;
    }
    return $header;
}

##------------------------------------------------------------------------------
sub gets
{
    if ( defined $_[0] )
    {
        print( ( defined $_[1] ) ? "$_[0] ($_[1]): " : "$_[0]: " );
    }
	my $ret = <STDIN>;
	chomp( $ret );
	$ret = $_[1] if ( ( $ret eq "" ) && ( defined $_[1] ) );
    return $ret;
}

##------------------------------------------------------------------------------
sub trim
{
    my $string = $_[0];
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}

##------------------------------------------------------------------------------
__DATA__
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
YCbCr Matrix: TV.601

[Aegisub Project Garbage]
Audio File: video.mp4
Video File: video.mp4
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 0.500000
Active Line: 7
Video Position: 3414

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: ICredit,Arial,36,&H00FFFFFF,&H0000FFFF,&H00000008,&H80000008,-1,0,0,0,100,100,0,0,1,3,0,2,93,93,40,0
Style: Default,Arial,18,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,3,2,27,27,20,1
Style: IScreenText,Georgia,58,&H00FDFFD6,&H00E48A84,&H00D02F00,&H80272733,0,0,0,0,100,100,0,0,1,2,3,2,93,93,50,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
